directory:
  model_dir: models
  report_dir: reports

names:
  model_name: model.pkl
  graph_name: graph.png
  report_name: classification_report.xlsx

database:
  db_name: finance1
  username: Rohit
  pwd: Mongodb

randomforestparams:
  n_estimators: [10,15,18,20]
  max_depth: [12,15,17,20]
  min_samples_split: [2,4,5]
  min_samples_leaf: [2,4,5]
  max_features: [6,5,7,11]
  class_weight: ['balanced']

xgboostparams: 
  learning_rate: [0.01,0.05,0.1,0.3,0.5]
  gamma: [0, 0.1, 0.2, 0.3, 0.4]
  max_depth: [2,3,4,5,6]
  min_child_weight: [1,2,5]
  max_delta_step: [0,1,2,5]
  subsample: [0.5, 0.6, 0.7, 0.8, 0.9]
  colsample_bytree: [0.5, 0.6, 0.7, 0.8, 0.9]
  colsample_bylevel: [0.5, 0.6, 0.7, 0.8, 0.9]
  reg_lambda: [0.1, 1, 100]
  reg_alpha: [0.1, 1, 100]
  scale_pos_weight: [1,2,3,4]
  n_estimators: [20,40,45,60]
  tree_method: ['gpu_hist']


